In [2]:
import sklearn

In [3]:
help(sklearn)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experime

In [4]:
print(sklearn.__version__)

1.2.2


## 첫 번째 머신러닝 - 붓꽃 품종 예측하기

In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [6]:
iris = load_iris()

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
iris_data = iris.data #독립변수
iris_data.shape

(150, 4)

In [10]:
iris_label = iris.target #종속변수

In [13]:
import numpy as np
np.unique(iris_label,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [14]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)

In [17]:
xa = [[x,x] for x in range(100)]
ya = [y for y in range(100)]

In [20]:
x_train,x_test, y_train,y_test = train_test_split(xa,ya)

In [22]:
np.array(x_train).shape, np.array(y_train).shape

((75, 2), (75,))

In [21]:
for i in range(len(x_train)):
  print(x_train[i],":",y_train[i])

[85, 85] : 85
[9, 9] : 9
[60, 60] : 60
[95, 95] : 95
[41, 41] : 41
[29, 29] : 29
[19, 19] : 19
[81, 81] : 81
[46, 46] : 46
[38, 38] : 38
[80, 80] : 80
[48, 48] : 48
[70, 70] : 70
[83, 83] : 83
[8, 8] : 8
[11, 11] : 11
[0, 0] : 0
[87, 87] : 87
[69, 69] : 69
[55, 55] : 55
[84, 84] : 84
[57, 57] : 57
[91, 91] : 91
[79, 79] : 79
[32, 32] : 32
[99, 99] : 99
[14, 14] : 14
[30, 30] : 30
[76, 76] : 76
[50, 50] : 50
[31, 31] : 31
[61, 61] : 61
[45, 45] : 45
[5, 5] : 5
[34, 34] : 34
[27, 27] : 27
[7, 7] : 7
[56, 56] : 56
[24, 24] : 24
[18, 18] : 18
[58, 58] : 58
[12, 12] : 12
[17, 17] : 17
[71, 71] : 71
[66, 66] : 66
[64, 64] : 64
[67, 67] : 67
[3, 3] : 3
[22, 22] : 22
[33, 33] : 33
[97, 97] : 97
[23, 23] : 23
[77, 77] : 77
[68, 68] : 68
[39, 39] : 39
[36, 36] : 36
[73, 73] : 73
[40, 40] : 40
[89, 89] : 89
[49, 49] : 49
[21, 21] : 21
[51, 51] : 51
[59, 59] : 59
[26, 26] : 26
[62, 62] : 62
[54, 54] : 54
[6, 6] : 6
[92, 92] : 92
[94, 94] : 94
[43, 43] : 43
[13, 13] : 13
[75, 75] : 75
[37, 37] : 37

In [23]:
x_train,x_test, y_train,y_test = train_test_split(
    iris_data,iris_label,test_size=0.2)

In [24]:
x_train.shape, x_test.shape

((120, 4), (30, 4))

In [26]:
model = DecisionTreeClassifier() #모델 생성
model.fit(x_train,y_train) #모델 학습

DecisionTreeClassifier()

In [28]:
pred = model.predict(x_test)

In [29]:
for i in range(len(pred)):
  print(pred[i],":",y_test[i])

0 : 0
1 : 1
0 : 0
1 : 1
2 : 2
1 : 1
1 : 1
2 : 2
2 : 2
0 : 0
2 : 2
1 : 1
2 : 2
1 : 1
0 : 0
0 : 0
1 : 1
1 : 1
1 : 1
0 : 0
2 : 2
2 : 2
2 : 1
1 : 2
2 : 2
1 : 1
1 : 1
2 : 2
0 : 0
1 : 1


In [30]:
print(pred)
print(y_test)

[0 1 0 1 2 1 1 2 2 0 2 1 2 1 0 0 1 1 1 0 2 2 2 1 2 1 1 2 0 1]
[0 1 0 1 2 1 1 2 2 0 2 1 2 1 0 0 1 1 1 0 2 2 1 2 2 1 1 2 0 1]


In [31]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(y_test,pred) #모델 평가

0.9333333333333333

#프레임워크 익히기

In [35]:
iris_data = load_iris()

In [36]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [37]:
print("특성:",iris_data.feature_names)

특성: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [38]:
print("특성 수:",len(iris_data.feature_names))

특성 수: 4


In [39]:
print("종속 변수 타입:",type(iris_data.target[0]))

종속 변수 타입: <class 'numpy.int64'>


In [40]:
print("독립변수 구조:",iris_data.data.shape)

독립변수 구조: (150, 4)


## Model Selection 모듈 소개

In [42]:
iris = load_iris()
train_data = iris.data #독립변수(data.feature.x)
train_label = iris.target #종속변수(label.target.y)

In [71]:
df = DecisionTreeClassifier()
df.fit(train_data,train_label)
pred = df.predict(train_data)
accuracy_score(pred,train_label)

1.0

In [45]:
x_train,x_test,y_train,y_test =train_test_split(
    iris.data,iris.target)

In [47]:
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9210526315789473

In [48]:
from sklearn.model_selection import KFold

In [84]:
iris = load_iris()
feature = iris.data
label = iris.target

In [50]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=5)

In [51]:
cv_accuracy=[]
n_iter = 0

In [86]:
list(kfold.split(feature))

[(array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
          63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
          76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
          89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
         141, 142, 143, 144, 145, 146, 147, 148, 149]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,

In [87]:
for train_ind, test_ind in kfold.split(feature):
    x_train,x_test = feature[train_ind], feature[test_ind]
    y_train,y_test = label[train_ind], label[test_ind]

    dt_clf.fit(x_train,y_train) #학습
    pred = dt_clf.predict(x_test) #예측
    n_iter+=1

    acc = np.round(accuracy_score(pred,y_test),3)
    print(n_iter,"회 교차 검증 accuracy:",acc)
    cv_accuracy.append(acc)
print("평균 accuracy:",np.mean(cv_accuracy))

4 회 교차 검증 accuracy: 0.0
5 회 교차 검증 accuracy: 0.0
6 회 교차 검증 accuracy: 0.0
평균 accuracy: 0.0


In [79]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['label']=iris.target
df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [80]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(df):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


In [75]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score,cross_validate

In [97]:
data = iris.data
label = iris.target

In [98]:
df = DecisionTreeClassifier()
scores = cross_validate(dt,data,label,scoring=['accuracy','precision','recall'],cv=3)
scores

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1954, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/usr/local/lib/python3.10/dist-packages/sk

{'fit_time': array([0.00108504, 0.00342512, 0.00106239]),
 'score_time': array([0.00784707, 0.00302935, 0.00276113]),
 'test_accuracy': array([0.66, 0.66, 0.66]),
 'test_precision': array([nan, nan, nan]),
 'test_recall': array([nan, nan, nan])}

In [127]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target)

In [128]:
params = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3,4]
}

In [129]:
from sklearn.model_selection import GridSearchCV

In [130]:
dtree = DecisionTreeClassifier()
gs = GridSearchCV(dtree,param_grid=params,cv=3,refit=True)
gs.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [131]:
gs.best_score_

0.9466571834992887

In [132]:
model = gs.best_estimator_

In [133]:
gs.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [134]:
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9473684210526315

## 전처리

In [135]:
from sklearn.preprocessing import LabelEncoder

In [136]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [138]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [140]:
items2 = ['TV','TV','냉장고','선풍기']
labels = encoder.transform(items2)
labels

array([0, 0, 1, 3])

In [142]:
#items3 = ['식기세척기','스타일러','슈즈스타일러']
#labels = encoder.transform(items3)
#labels

In [143]:
from sklearn.preprocessing import OneHotEncoder

In [145]:
items = np.array(items).reshape(-1,1)

In [147]:
ohe = OneHotEncoder()
ohe.fit(items)
labels = ohe.transform(items)
labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [148]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
df = pd.get_dummies(items)

In [149]:
df

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [150]:
from scipy import stats

In [155]:
heights = stats.norm.rvs(loc=173,scale=4,size=1000)
bmis = stats.norm.rvs(loc=21,scale=2,size=1000)
weights = bmis*(heights**2)/10000

In [161]:
c_sizes = [ (heights[i]*2+weights[i]*2)/5  for i in range(1000)]
c_sizes = np.array(c_sizes)

In [162]:
from sklearn.neighbors import KNeighborsRegressor

In [165]:
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values

In [166]:
label = c_sizes

In [167]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [168]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [169]:
knn.score(x_test,y_test)

0.9938468683639738

In [170]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [172]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [173]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [174]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [179]:
ss = StandardScaler()
ss.fit(df)
scaled = ss.transform(df)
np.round(scaled.mean(),10),scaled.var()

(-0.0, 1.0)

In [181]:
df2 = pd.DataFrame(scaled)
filter = df2[0]<-3
filter.value_counts()

False    150
Name: 0, dtype: int64

In [182]:
df2.describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -1.468455e-15 -1.823726e-15 -1.610564e-15 -9.473903e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.433947e+00 -1.567576e+00 -1.447076e+00
25%   -9.006812e-01 -5.923730e-01 -1.226552e+00 -1.183812e+00
50%   -5.250608e-02 -1.319795e-01  3.364776e-01  1.325097e-01
75%    6.745011e-01  5.586108e-01  7.627583e-01  7.906707e-01
max    2.492019e+00  3.090775e+00  1.785832e+00  1.712096e+00

In [185]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9954194857118388

In [186]:
x_train, x_test, y_train,y_test = train_test_split(data,label)

In [190]:
mms1 = MinMaxScaler()
mms1.fit(x_train)
scaled_train = mms1.transform(x_train)

In [191]:
mms2 = MinMaxScaler()
mms2.fit(x_test)
scaled_train = mms2.transform(x_test)

In [192]:
x_test.shape

(250, 2)

In [193]:
sample = [[1.75,89],[1.72,62]]
mms1.transform(sample)

array([[-7.03529493,  1.00941342],
       [-7.03661157,  0.41652692]])

In [194]:
sample = [[1.75,89],[1.72,62]]
mms2.transform(sample)

array([[-6.83531634,  1.32352718],
       [-6.83659919,  0.42667816]])